services:
  php:
    build:
      context: .
      dockerfile: Docker/PHP/Dockerfile
    volumes:
      - ./volumes/www:/var/www
    ports:
      - "9000:9000"
    command: /bin/bash setup.sh
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./volumes/www:/var/www
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
volumes:
  db_data:
