services:
  php:
    build:
      context: .
      dockerfile: Docker/PHP/Dockerfile
    volumes:
      - ./volumes/www:/var/www
    ports:
      - "9000:9000"
    command: /bin/bash setup.sh
    networks:
      - bridge-network
    depends_on:
      - db

  php2:
    build:
      context: .
      dockerfile: Docker/PHP/Dockerfile
    volumes:
      - ./volumes/www2:/var/www
    ports:
      - "9001:9000"
    command: /bin/bash setup.sh
    networks:
      - bridge-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - bridge-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./volumes/www:/var/www
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - bridge-network
  nginx2:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./volumes/www2:/var/www
      - ./volumes/nginx/default2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
      - db
    networks:
      - bridge-network

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bridge-network
volumes:
  db_data:
networks:
  bridge-network:
    driver: bridge
